export * from './article.interface';
export * from './category.interface';
export * from './comment.interface';
export * from './content.interface';
export * from './custom.interface';
export * from './media.interface';
export * from './page.interface';
export * from './photo.interface';
export * from './widget.interface';