const HTTP_ERROR_SUFFIX = '失败';
const HTTP_SUCCESS_SUFFIX = '成功';
const HTTP_DEFAULT_TEXT = '数据请求';
const HTTP_DEFAULT_ERROR_TEXT = HTTP_DEFAULT_TEXT + HTTP_ERROR_SUFFIX;
const HTTP_DEFAULT_SUCCESS_TEXT = HTTP_DEFAULT_TEXT + HTTP_SUCCESS_SUFFIX;
const HTTP_UNAUTHORIZED_TEXT_DEFAULT = '权限验证失败';
const HTTP_BAD_REQUEST_TEXT_DEFAULT = '未知错误';
const HTTP_PARAMS_PERMISSION_ERROR_DEFAULT = '无权使用参数';
const VALIDATION_ERROR_DEFAULT = '参数验证失败';

export const TEXT = {
  HTTP_ERROR_SUFFIX,
  HTTP_SUCCESS_SUFFIX,
  HTTP_DEFAULT_TEXT,
  HTTP_DEFAULT_ERROR_TEXT,
  HTTP_DEFAULT_SUCCESS_TEXT,
  HTTP_UNAUTHORIZED_TEXT_DEFAULT,
  HTTP_BAD_REQUEST_TEXT_DEFAULT,
  HTTP_PARAMS_PERMISSION_ERROR_DEFAULT,
  VALIDATION_ERROR_DEFAULT,
};
